logging.config: "classpath:log4jconfig/log4j2-prd.xml"

spring:
  kafka:
    bootstrap-servers: broker1.prd.kafka.emobility:9092,broker2.prd.kafka.emobility:9092,broker3.prd.kafka.emobility:9092
  datasource:
    url: jdbc:postgresql://station-configuration-postgres-prd.postgres.database.azure.com:5432/station_configuration_prd
    username: qx7gkejq@station-configuration-postgres-prd
    password: 82FTNnGyV5UU9bRu
    hikari:
      maximumPoolSize: 50
  azure:
    blob:
      store:
        DefaultEndpointsProtocol: https://stationconfigurationdev.blob.core.windows.net/media/
        connectionString: "DefaultEndpointsProtocol=https;AccountName=stationconfigurationprd;AccountKey=y8Q+QGwYQ0HS3wOT5kp7U8PiMZia7jNNEBd8xXjj/FMwgj/FDqjMZBR13YaEzm/DdROLlRSUZbVoFki5YcVrhQ==;EndpointSuffix=core.windows.net"
        containerName: "media"

azure:
  application-insights:
    instrumentation-key: 04156aa9-66f5-49ac-a733-953c1ad6652d

swagger:
  baseUrl: emobility-cloud.vattenfall.com
  basePath: station-configuration

emobility:
  url: http://backend.old-platform/backend/external-ws/mvc/
  username: prometheus_user
  password: Wakx4betk_b3

features:
  catalogue:
    default:
      image:
        id: 42505e98-c97b-4d45-af9c-cc62c6877992
