spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

emobility:
  url: https://backend.goincharge.com/external-ws/mvc/
  username: prometheus_user
  password: Wakx4betk_b3
