logging.config: "classpath:log4jconfig/log4j2-dev.xml"
logging:
  level:
    org:
      apache:
        http: DEBUG
    httpclient:
      wire: DEBUG

spring:
  kafka:
    bootstrap-servers: broker1.dev.kafka.emobility:9092,broker2.dev.kafka.emobility:9092,broker3.dev.kafka.emobility:9092
  datasource:
    url: jdbc:postgresql://station-configuration-postgresql-dev-tst.postgres.database.azure.com:5432/station_configuration_dev
    username: drq6k5orrd@station-configuration-postgresql-dev-tst
    password: 29O8VerLW5
  azure:
    blob:
      store:
        DefaultEndpointsProtocol: https://stationconfigurationdev.blob.core.windows.net/media/
        connectionString: "DefaultEndpointsProtocol=https;AccountName=stationconfigurationdev;AccountKey=i3649cngze4CzP/6+ZOEcKw+tCtmVDyv5NgPje+jt8zVg1PS9Z5uBBfOyycfcqUicOcM+vvpCM3Z7irojnKYUQ==;EndpointSuffix=core.windows.net"
        containerName: "media"

azure:
  application-insights:
    instrumentation-key: 4fb8cc26-b757-4f4c-a5a1-5fc988b9e822

swagger:
  baseUrl: emobility-cloud-dev.vattenfall.com
  basePath: station-configuration-dev

emobility:
  url: http://backend.old-platform/backend/external-ws/mvc
  username: abo17
  password: 123qwe

features:
  catalogue:
    default:
      image:
        id: 8a201486-2780-482f-8044-2363f2dbd914
